/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prueba */

#ifndef _Included_prueba
#define _Included_prueba
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prueba
 * Method:    sumar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_prueba_sumar
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
