/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvideo */

#ifndef _Included_cvideo
#define _Included_cvideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvideo
 * Method:    startvideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cvideo_startvideo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
